/**
 * The source catalogue.
 *
 * Every other language is typed as `Catalog`, so a missing or misspelled key
 * is a compile error rather than a string that quietly falls back to English
 * in front of someone who does not read English. Values that take arguments
 * are functions for the same reason: a translation cannot silently drop the
 * number it was supposed to interpolate.
 *
 * Keep the wording here as plain as the interface: these strings explain what
 * the hardware did, and a translation that reaches for marketing language
 * breaks the one thing this application is for.
 */
export const en = {
  meta: {
    /** Shown in the language picker, in the language itself. */
    name: "English",
  },

  app: {
    name: "Gear Control Center",
    tagline: "Local · Open hardware",
    sections: "Sections",
    connection: "Connection",
    noDeviceDetected: "No device detected",
    lookingForDevices: "Looking for devices",
    commandFailed: "Device command failed",
    dismiss: "Dismiss",
  },

  nav: {
    sensor: "Sensor",
    lighting: "Lighting",
    dashboard: "Dashboard",
    audio: "Audio",
    microphone: "Microphone",
    equaliser: "Equaliser",
    profiles: "Profiles",
    device: "Device",
    settings: "Settings",
  },

  connection: {
    connected: "Connected",
    disconnected: "Disconnected",
    connecting: "Connecting",
    reconnecting: "Reconnecting",
    unknown: "Unknown",
    error: "Error",
  },

  strip: {
    device: "Device",
    link: "Link",
    battery: "Battery",
    chatmix: "ChatMix",
    noDevice: "No device",
    poweredOn: "Headset powered on",
    poweredOff: "Headset powered off",
    charging: "Charging",
    reportedLevels: (count: number) => `${count} reported levels`,
    notSupported: "Not supported",
    notReportedWhileOff: "Not reported while off",
  },

  empty: {
    title: "No compatible device detected",
    lede: "Nothing this application knows how to talk to is connected right now.",
    hints: [
      "Check that the wireless dongle is plugged in.",
      "Switch the headset on and wait a few seconds for it to pair.",
      "Close any other software that controls the headset — only one application can hold the device at a time.",
    ],
    scanning: "Scanning",
    scanAgain: "Scan again",
    useSimulated: "Use a simulated device",
  },

  conflict: {
    title: (name: string) => `${name} is connected but cannot be opened`,
    useSimulatedInstead: "Work with a simulated device instead",
    explain:
      "Another application is holding the control interface. On this system that is usually a background service; stopping it releases the headset:",
    nothingChanged:
      "Nothing on your system has been changed — run that yourself if you want this application to take over, and re-enable it later with:",
  },

  dashboard: {
    hostErrorTitle: "Hardware access unavailable",
    simulatedTitle: "Simulated device",
    simulatedBody:
      "These readings are generated by the application, not by a headset. Turn this off in Settings once real hardware is connected.",

    controlsLegend: "Controls",
    controlsTitle: "Quick controls",
    outputVolume: "Output volume",
    hardwareSteps: (count: number) => `${count} hardware steps`,
    mute: "Mute",
    unmute: "Unmute",
    muteMic: "Mute mic",
    unmuteMic: "Unmute mic",
    sidetone: "Sidetone",

    powerLegend: "Power",
    batteryTitle: "Battery",
    chargingOverUsb: "Charging over USB",
    lowChargeSoon: "Low — charge soon",
    runningOnBattery: "Running on battery",
    batteryResolution: (levels: number) =>
      `This device reports ${levels} levels rather than a percentage, so this figure moves in steps. It is what the device sent, not an estimate.`,
    batteryOff:
      "The device is not reporting a battery level — it is switched off or asleep.",
    batteryUnsupported: "This device does not report a battery level.",

    mixLegend: "Mix",
    chatmixTitle: "ChatMix",
    game: "Game",
    chat: "Chat",
    chatmixExplain:
      "The dial is on the headset itself. This shows where it is set; it cannot be moved from here.",
    chatmixOff:
      "The headset is switched off, so the dial position is not being reported.",
    chatmixUnsupported: "This device has no ChatMix dial.",

    statusLegend: "Status",
    liveTitle: "Live readings",
    liveDescription: "Values as last received from the device.",
    power: "Power",
    on: "On",
    off: "Off",
    autoShutOff: "Auto shut-off",
    equaliser: "Equaliser",
    minutes: (count: number) => `${count} min`,
    custom: "Custom",
    notReadBack: "Not read back",
    notSupported: "Not supported",
    notReadBackExplain:
      '"Not read back" means the device accepts the setting but offers no way to ask for its current value. This build shows what it was told, and shows nothing after a reconnect rather than guessing.',
  },

  audio: {
    noDeviceTitle: "No device connected",
    noDeviceBody: "Connect a headset to control its volume.",
    noControlTitle: "No volume control on this device",
    cardUnreadable: "The device's audio card could not be read.",
    noHardwareVolume: "This headset does not expose a hardware volume control.",

    outputLegend: "Output",
    volumeTitle: "Volume",
    volumeDescription:
      "The headset's own volume, the same control as the dial on the cup.",
    muted: "Muted",
    mute: "Mute",
    gain: "Gain",
    outputLevel: "Output level",
    levelDetail: (steps: number) =>
      `${steps} hardware steps. Changing this changes the headset for every application, not just this one.`,
    mutedTitle: "Output is muted",
    mutedBody: "The level control is disabled while the headset is muted.",

    notAvailableLegend: "Not available",
    notAvailableTitle: "What this device does not do",
    absent: [
      {
        name: "Volume limiter",
        detail: "No maximum-level clamp exists in the hardware.",
      },
      { name: "Spatial audio", detail: "Not a feature of this headset." },
      {
        name: "Software equaliser",
        detail:
          "The equaliser is applied by the headset itself — see the Equaliser page.",
      },
    ],
  },

  microphone: {
    noDeviceTitle: "No device connected",
    noDeviceBody: "Connect a headset to control its microphone.",

    inputLegend: "Input",
    title: "Microphone",
    description: "The capture gain on the headset's own audio hardware.",
    muted: "Muted",
    mute: "Mute",
    gain: "Gain",
    captureLevel: "Capture level",
    levelDetail: (steps: number) => `${steps} hardware steps.`,
    mutedTitle: "Microphone is muted",
    mutedBody:
      "Nothing is being captured. This is the hardware mute, so it applies to every application.",
    noControl: "This device exposes no microphone control.",

    monitoringLegend: "Monitoring",
    sidetoneTitle: "Sidetone",
    sidetoneDescription:
      "How much of your own voice the headset plays back to you.",
    level: "Level",
    sidetoneSteps: (count: number) =>
      `The headset stores ${count} positions, so this is a switch rather than a slider.`,
    sidetoneUnknown:
      " It does not report which one is currently set — the selection appears here once you choose it.",
    sidetoneUnsupported: "This device has no sidetone control.",

    processingLegend: "Not available",
    processingTitle: "Microphone processing",
    processingBody:
      "This headset performs no processing on the microphone signal. None of the following exist in its hardware, and this application will not apply them in software and call them a device feature:",
    processingList: [
      "Noise reduction",
      "Noise gate",
      "Compressor",
      "Limiter",
      "Voice enhancement",
      "Microphone mute LED",
    ],
  },

  equaliser: {
    unavailableTitle: "No equaliser available",
    noEqualiser: "This device has no equaliser.",
    connectFirst: "Connect a headset to adjust its equaliser.",

    toneLegend: "Tone",
    title: "Equaliser",
    hardwareDescription:
      "Applied by the headset itself — it stays in effect for every application, and for anything else this headset is plugged into.",
    softwareDescription: "Applied by this application.",
    flat: "Flat",
    presets: "Presets",
    custom: "Custom",
    bandLabel: (frequency: string) => `${frequency} band`,
    bandValue: (decibels: string, frequency: string) =>
      `${decibels} decibels at ${frequency}`,
    range: (bands: number, min: number, max: number, step: number) =>
      `${bands} bands · ${min} to +${max} dB · ${step} dB steps`,
    frequenciesAreLabels:
      "Band frequencies are labels: the headset accepts ten positional gains and never names them, so these follow the standard ten-band spacing.",
    noReadBackTitle: "The headset does not report its curve",
    noReadBackBody:
      "There is no command to ask this device what its equaliser is currently set to. The faders start flat after a reconnect and show what this application has sent since — not necessarily what the headset is applying. Choosing a preset or moving a fader makes the two agree.",
  },

  profiles: {
    savedLegend: "Saved",
    title: "Profiles",
    description:
      "Settings kept by this application and sent to the headset on request.",
    saveAs: "Save the current settings as",
    placeholder: "Late night, Voice call, Games…",
    save: "Save",
    noDeviceTitle: "No device connected",
    noDeviceBody:
      "Profiles can be applied and edited only while a headset is connected — there is nothing to read the current settings from.",
    failedTitle: "That did not work",
    empty:
      "No profiles yet. Set the headset up the way you want it, then save it here.",
    lastApplied: "last applied",
    nothingStored: "Nothing stored",
    apply: "Apply",
    rename: (name: string) => `Rename ${name}`,
    remove: (name: string) => `Delete ${name}`,
    confirmRename: "Confirm rename",
    cancelRename: "Cancel rename",

    resultLegend: "Result",
    resultTitle: (name: string) => `Applied "${name}"`,
    sent: (settings: string) => `Sent to the headset: ${settings}.`,
    nothingSent: "This profile holds no settings, so nothing was sent.",

    howLegend: "How this works",
    howTitle: "Profiles live here, not on the headset",
    howBody1:
      'This headset has no onboard memory for settings, so there is no "save to device" button here — there is no such command in its protocol. Applying a profile sends each setting to the device one at a time, exactly as if you had set them by hand.',
    howBody2:
      "That also means the headset can be changed from its own controls without this application knowing. A profile marked as last applied is a record of what was sent, not a claim about what the hardware is currently doing.",

    contents: {
      volume: "Volume",
      muted: "Muted",
      unmuted: "Unmuted",
      micLevel: "Mic level",
      micMuted: "Mic muted",
      micLive: "Mic live",
      sidetone: "Sidetone",
      autoShutOff: "Auto shut-off",
      equaliserCurve: "Equaliser curve",
      equaliserPreset: "Equaliser preset",
    },
  },

  chatmix: {
    splitTitle: "Split game and chat audio",
    splitDetail:
      "Adds two outputs — Headset — Game and Headset — Chat — and mixes both into the headset. The wheel then sets the balance between them, which is what it is for.",
    splitDisabledReason: "Connect the headset first.",
    activeTitle: "The game and chat outputs are in place",
    activeBody:
      "Assign each application to Headset — Game or Headset — Chat in your usual volume control. Turning the wheel changes the balance between them.",
    failedTitle: "The outputs could not be created",
    note: "This changes the audio devices for your whole session, not only for this application. Turning it off removes them again, and so does quitting.",
  },

  device: {
    hardwareLegend: "Hardware",
    identityTitle: "Identity",
    simulatedDescription:
      "A simulated device — these values are fixed, not read from hardware.",
    realDescription: "Read from the connected device.",
    scanning: "Scanning",
    rescan: "Rescan",
    product: "Product",
    vendorId: "Vendor ID",
    productId: "Product ID",
    connection: "Connection",
    serial: "Serial number",
    firmware: "Firmware version",
    revision: "Hardware revision",
    source: "Source",
    simulated: "Simulated",
    physical: "Physical device",
    notAvailable: "N/A",
    nothingToReport: "No device is connected, so there is nothing to report.",
    naExplain:
      "Fields marked N/A are not exposed by this headset over its control interface. They are left empty rather than filled in from a product database.",

    unverifiedTitle: "This build has not been checked against your headset",
    unverifiedBody:
      "Support for this model was written from published documentation that two independent projects agree on, but nobody has run it against the hardware. So it reads from your headset and will not write to it: a command nobody has seen answered is not one to send blind.",
    unverifiedHelp:
      "If you have this headset and the readings above match what it reports elsewhere, say so in an issue and the controls can be turned on.",
    detectedLegend: "Detected",
    detectedTitle: "Devices on this system",
    detectedDescription:
      "Every supported device found, including ones that cannot currently be opened.",
    scanningEllipsis: "Scanning…",
    nothingFound: "Nothing found.",
    available: "Available",
    connect: "Connect",
    connected: "Connected",

    powerLegend: "Power",
    autoShutOffTitle: "Auto shut-off",
    autoShutOffDescription:
      "How long the headset waits, with no audio and no movement, before switching itself off to save battery.",
    idleTimeout: "Idle timeout",
    never: "Never",
    minutes: (count: number) => `${count} min`,
    autoShutOffDetail: (max: number) =>
      `The headset accepts 0 to ${max} minutes. Zero disables the timer entirely.`,
    autoShutOffUnknown:
      "The headset does not report its current timeout, so this starts at zero after a reconnect and shows what this application has sent since.",

    capabilitiesLegend: "Capabilities",
    capabilitiesTitle: "What this device can do",
    capabilitiesDescription:
      "Reported by the hardware, not assumed from its model name.",
    supported: "supported",
    unsupported: "not supported",
  },

  settings: {
    settingFailed: "That setting was not applied",

    startupLegend: "Startup",
    startupTitle: "Launching",
    startWithSystem: "Start with the system",
    startWithSystemDetail:
      "Adds a desktop entry to your autostart directory. Nothing is installed system-wide.",
    startMinimised: "Start in the tray",
    startMinimisedDetail: "Launch without opening the window.",
    startMinimisedDisabled:
      "Available once the application starts with the system.",
    closeToTray: "Closing the window keeps it running",
    closeToTrayDetail:
      "The headset keeps being read, and the tray entry stays available. Quit from the tray menu to stop it completely.",

    languageLegend: "Language",
    languageTitle: "Interface language",
    languageDescription:
      "Applies immediately, including the tray menu and notifications.",
    systemLanguage: "Match the system",
    languageNote:
      "Readings from the device are never translated: a decibel is a decibel, and a model name is what the hardware calls itself.",

    alertsLegend: "Alerts",
    alertsTitle: "Notifications",
    lowBattery: "Warn when the battery gets low",
    lowBatteryDetail:
      "Shown once as the level drops past the threshold, not repeatedly.",
    threshold: "Threshold",
    thresholdNote:
      "Only these two are offered because they are the levels every supported device can report: a headset reports five — 0, 25, 50, 75 and 100 per cent — and a mouse reports in steps of five. A threshold of 30% would be waiting for a number a headset never sends.",

    developmentLegend: "Development",
    simulatedTitle: "Simulated device",
    simulatedDescription: "For working on the interface without hardware attached.",
    useSimulated: "Use a simulated device",
    useSimulatedDetail:
      "Replaces the headset with a stand-in that reports the same capabilities and the same resolution. Every reading is clearly marked as simulated.",
    simulationOnTitle: "Simulation is on",
    simulationOnBody:
      "No physical headset is being read or written while this is enabled.",

    supportLegend: "Support",
    diagnosticsTitle: "Diagnostics",
    diagnosticsDescription:
      "A plain-text report of what this application can see, for attaching to a bug report.",
    writeReport: "Write report",
    writtenTo: "Written to",
    diagnosticsBody:
      "Contains device identifiers, capabilities, the last readings and your settings. It contains nothing about you, and it is not sent anywhere — the file stays on this machine.",

    aboutLegend: "Application",
    aboutTitle: "About",
    aboutBody1:
      "A local application for controlling supported headsets directly over USB. Nothing is sent anywhere: there is no account, no telemetry and no network connection.",
    aboutBody2:
      "Device support is built on publicly documented protocols. Where a command has not been verified against hardware, the feature is marked unsupported rather than shipped on a guess.",
    version: (version: string) => `Version ${version} · Linux`,
    versionUnavailable: "Version unavailable · Linux",
    loading: "Loading…",
  },

  capabilities: {
    batteryLevel: "Battery level",
    batteryLevelDetail: (steps: number, apart: number) =>
      `${steps} discrete levels, ${apart}% apart`,
    batteryLevelAbsent: "Not reported by this device",
    chargingState: "Charging state",
    chargingStateDetail: "Reported while the cable is attached",
    chatmix: "ChatMix dial",
    chatmixDetail: "Read-only — the wheel is on the headset",
    chatmixAbsent: "Not present on this device",
    sidetone: "Sidetone",
    sidetoneDetail: (count: number, labels: string) =>
      `${count} hardware steps: ${labels}`,
    sidetoneAbsent: "Not adjustable on this device",
    equaliser: "Equaliser",
    equaliserDetail: (bands: number, min: number, max: number, step: number) =>
      `${bands} bands, ${min} to +${max} dB in ${step} dB steps`,
    equaliserHardware: " — applied by the headset itself",
    equaliserAbsent: "Not available on this device",
    presets: "Equaliser presets",
    presetsAbsent: "No stored presets",
    inactiveTime: "Auto shut-off timer",
    inactiveTimeDetail: (max: number) => `Up to ${max} minutes`,
    inactiveTimeAbsent: "Not adjustable on this device",
    volume: "Output volume",
    volumeDetail: "USB audio hardware volume",
    mute: "Output mute",
    muteDetail: "USB audio hardware mute",
    notExposed: "Not exposed by this device",
    micVolume: "Microphone volume",
    micVolumeDetail: "USB audio capture gain",
    micMute: "Microphone mute",
    micMuteDetail: "USB audio capture mute",
    softwareProfiles: "Software profiles",
    softwareProfilesDetail:
      "Stored by this application and sent to the headset on demand",
    onboardProfiles: "Onboard profile memory",
    onboardProfilesDetail: "Settings persist on the headset",
    onboardProfilesAbsent:
      "The headset cannot store profiles, so there is nothing to save to it",
    firmware: "Firmware update",
    firmwareAbsent: "No documented update path for this device",
    dpi: "Sensor resolution",
    dpiDetail: (count: number, min: number, max: number) =>
      `${count} steps, ${min}-${max} CPI`,
    dpiAbsent: "This device has no sensor",
    pollingRate: "Report rate",
    pollingRateDetail: (rates: string) => `${rates}`,
    pollingRateAbsent: "Not adjustable on this device",
    lightingZones: "Lighting zones",
    lightingZonesDetail: (zones: string) => zones,
    lightingZonesAbsent: "No addressable zones",
    onboardMemory: "Onboard memory",
    onboardMemoryDetail: "Settings can be written to the device itself",
    onboardMemoryAbsent: "The device stores nothing of its own",
    rgb: "RGB lighting",
    rgbAbsent: "This headset has no addressable lighting",
    spatial: "Spatial audio",
    spatialAbsent: "Not a hardware feature here",
    noiseReduction: "Hardware noise reduction",
    noiseReductionAbsent:
      "No microphone gate, compressor or limiter on the device",
    supported: "Supported",
    notAvailable: "Not available",
  },

  /**
   * Short words the device layer supplies as identifiers rather than prose:
   * sidetone steps and firmware preset names. They are looked up by a
   * normalised key and fall back to the raw string, so a device with terms
   * nobody has translated yet still shows something true.
   */
  devices: {
    title: "Devices",
    readOnly: "Read-only",
    off: "Off",
    noReading: "No reading",
  },

  sensor: {
    title: "Sensor",
    lede: "The resolutions this mouse steps through, and how often it reports.",
    presets: "Resolution presets",
    presetsHint: (max: number) =>
      `Up to ${max}. The button under the mouse steps through them in order.`,
    preset: (n: number) => `Preset ${n}`,
    selected: "Selected",
    select: "Select this preset",
    add: "Add a preset",
    remove: "Remove",
    cpi: "CPI",
    snapped: (cpi: number) => `Nearest the sensor has: ${cpi} CPI`,
    reportRate: "Report rate",
    reportRateHint: "How often the mouse reports its position. Higher costs battery.",
    hz: (n: number) => `${n} Hz`,
    sleepTimer: "Sleep timer",
    sleepTimerHint: (max: number) =>
      `Idle minutes before the mouse powers itself down. Up to ${max}.`,
    never: "Never",
    minutes: (n: number) => `${n} min`,
    save: "Save to the mouse",
    saveHint:
      "These are re-sent whenever the mouse wakes. Saving also puts them in the mouse's own memory, so they survive without this application running.",
    saved: "Saved to the device",
    absent: "The selected device has no sensor to configure.",
  },

  lighting: {
    title: "Lighting",
    lede: "Three LEDs along the shell of the mouse.",
    effect: "Effect",
    effectHint:
      "Setting a colour is what stops the rainbow — the device has no separate command for it.",
    zones: "Zone colours",
    reactive: "Flash on click",
    reactiveHint: "A colour shown briefly each time a button is pressed.",
    reactiveOff: "Off",
    dim: "Dim after",
    dimHint: "Idle seconds before the lighting fades. Zero never dims.",
    seconds: (n: number) => `${n} s`,
    absent: "The selected device has no addressable lighting.",
  },
  terms: {
    top: "Top",
    middle: "Middle",
    bottom: "Bottom",
    static: "Static",
    rainbow: "Rainbow",
    off: "Off",
    low: "Low",
    medium: "Medium",
    high: "High",
    flat: "Flat",
    bassboost: "Bass Boost",
    smiley: "Smiley",
    focus: "Focus",
  },

  errors: {
    unverified:
      "This build has not been verified against your headset, so it only reads from it.",
    unsupported: "This feature is not supported by your device.",
    busy: "Another application is currently controlling the device.",
    offline: "The headset is turned off.",
    notConnected: "No device is connected.",
    transport: "Unable to communicate with the device.",
    protocol: "The device sent an unexpected response.",
    invalidParameter: "That value is outside what the device accepts.",
    failed: (action: string) => `${action} failed.`,
  },

  actions: {
    settingResolution: "Setting the resolution",
    settingReportRate: "Setting the report rate",
    settingLighting: "Setting the lighting",
    savingToDevice: "Saving to the device",
    switchingDevice: "Switching device",
    settingVolume: "Setting the volume",
    changingMute: "Changing mute",
    settingMicLevel: "Setting the microphone level",
    changingMicMute: "Changing the microphone mute",
    settingSidetone: "Setting sidetone",
    settingEqualiser: "Setting the equaliser",
    applyingPreset: "Applying an equaliser preset",
    settingAutoShutOff: "Setting the auto shut-off timer",
    readingState: "Reading device state",
    scanning: "Scanning for devices",
    connecting: "Connecting",
  },

  /**
   * Drawn by the native layer, which is handed these on startup and whenever
   * the language changes. They are templates rather than functions because
   * Rust does the substitution: `{percent}` and `{device}` are filled in
   * there, and a translation may move them wherever its grammar needs.
   */
  tray: {
    noDevice: "No device detected",
    batteryUnknown: "Battery: —",
    batteryNotReported: "Battery: not reported",
    battery: "Battery: {percent}%",
    batteryCharging: "Battery: {percent}% · charging",
    muteOutput: "Mute output",
    unmuteOutput: "Unmute output",
    muteMicrophone: "Mute microphone",
    unmuteMicrophone: "Unmute microphone",
    open: "Open Gear Control Center",
    quit: "Quit",
    lowBatteryTitle: "{device} battery is low",
    lowBatteryBody: "{percent}% remaining.",
  },
} satisfies Record<string, unknown>;

export type Catalog = typeof en;
